<?php

namespace Tests\Traits;

use App\Models\Label;
use App\Models\Task;
use App\Models\TaskStatus;
use App\Models\User;

trait Helpers
{
    protected User $user;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create();
    }

    protected function createTask(User $user, TaskStatus $taskStatus, ?Label $label = null): Task
    {
        $task = new Task();
        $task->name = 'Test task';
        $task->description = 'Task description';
        $task->created_by_id = $user->id;
        $task->assigned_to_id = $user->id;
        $task->status_id = $taskStatus->id;
        $task->save();
        if (!is_null($label)) {
            $task->labels()->attach($label);
            $task->save();
        }

        return $task;
    }

    protected function createTaskStatus(): TaskStatus
    {
        $taskStatus = new TaskStatus();
        $taskStatus->name = 'Test status';
        $taskStatus->save();

        return $taskStatus;
    }

    protected function createLabel(): Label
    {
        $label = new Label();
        $label->name = 'Test label';
        $label->description = 'Test label descr';
        $label->save();

        return $label;
    }
}
